package org.mercurydb.queryutils;

/**
 * This class defines two accessors for data
 * in a JoinStream. Note that JoinStream implements
 * JoinField. It provides a way for JoinStreams to
 * ask other JoinStreams how to extract a join key given
 * an instance of their class owner.
 */
public interface FieldExtractable<T> {
	/**
	 * Returns the name of the class owner. Note
	 * that the parameter to extractJoinKey should
	 * always be of this type. Ex. For a JoinStream
	 * from ATable, this should return A.class
	 * @return a Class
	 */
	public Class<?> getContainerClass();
	
	/**
	 * Extracts a join key value from an instance of the
	 * type returned by getClassOwner()
	 * @param o
	 * @return
	 */
	public T extractField(Object o);
	
	
	/**
	 * @return true if field is indexed, false otherwise
	 */
	public boolean isIndexed();
	
	/**
	 * Returns the id generated by the HgDB bootstrap process. This
	 * is the JOIN_ID in the tables. JOIN_ID should be packaged into
	 * produced FieldExtractable instances in this way.
	 * 
	 * @return id generated by the HgDB bootstrap process.
	 */
	public int getContainerId();
}
